/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import geradorxml.CorretorOrtografico;
import geradorxml.XML;
import javax.swing.JOptionPane;

/**
 *
 * @author Hiago
 */
public class D_IdentificacaoPAF extends javax.swing.JFrame {

    public static boolean isEdit1() {
        return edit1;
    }

    public static String getNomeComercial() {
        return nomeComercial;
    }

    public static void setEdit1(boolean edit1) {
        D_IdentificacaoPAF.edit1 = edit1;
    }

    public static boolean isEdit2() {
        return edit2;
    }

    public static void setEdit2(boolean edit2) {
        D_IdentificacaoPAF.edit2 = edit2;
    }

    public static boolean isEdit3() {
        return edit3;
    }

    public static void setEdit3(boolean edit3) {
        D_IdentificacaoPAF.edit3 = edit3;
    }

    public static boolean isEdit4() {
        return edit4;
    }

    public static void setEdit4(boolean edit4) {
        D_IdentificacaoPAF.edit4 = edit4;
    }

    public static boolean isEdit5() {
        return edit5;
    }

    public static void setEdit5(boolean edit5) {
        D_IdentificacaoPAF.edit5 = edit5;
    }

    public static boolean isEdit6() {
        return edit6;
    }

    public static void setEdit6(boolean edit6) {
        D_IdentificacaoPAF.edit6 = edit6;
    }

    public static boolean isEdit7() {
        return edit7;
    }

    public static void setEdit7(boolean edit7) {
        D_IdentificacaoPAF.edit7 = edit7;
    }

    public static boolean isEdit8() {
        return edit8;
    }

    public static void setEdit8(boolean edit8) {
        D_IdentificacaoPAF.edit8 = edit8;
    }

    public static boolean isEdit9() {
        return edit9;
    }

    public static void setEdit9(boolean edit9) {
        D_IdentificacaoPAF.edit9 = edit9;
    }

    public static boolean isEdit10() {
        return edit10;
    }

    public static void setEdit10(boolean edit10) {
        D_IdentificacaoPAF.edit10 = edit10;
    }

    public static boolean isEdit11() {
        return edit11;
    }

    public static void setEdit11(boolean edit11) {
        D_IdentificacaoPAF.edit11 = edit11;
    }

    public static boolean isEdit12() {
        return edit12;
    }

    public static void setEdit12(boolean edit12) {
        D_IdentificacaoPAF.edit12 = edit12;
    }

    public static boolean isEdit13() {
        return edit13;
    }

    public static void setEdit13(boolean edit13) {
        D_IdentificacaoPAF.edit13 = edit13;
    }

    public static boolean isEdit14() {
        return edit14;
    }

    public static void setEdit14(boolean edit14) {
        D_IdentificacaoPAF.edit14 = edit14;
    }

    public static boolean isEdit15() {
        return edit15;
    }

    public static void setEdit15(boolean edit15) {
        D_IdentificacaoPAF.edit15 = edit15;
    }

    /**
     * Creates new form
     */
    static boolean flag = false;
    static boolean edit1 = false, edit2 = false, edit3 = false, edit4 = false, edit5 = false, edit6 = false,
            edit7 = false, edit8 = false, edit9 = false, edit10 = false, edit11 = false, edit12 = false, edit13 = false,
            edit14 = false, edit15 = false;
    static String nomeComercial;

    public D_IdentificacaoPAF() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNomeComercial = new javax.swing.JTextField();
        jtVersao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtNomeExe = new javax.swing.JTextField();
        jtMdExe = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtNomeLista = new javax.swing.JTextField();
        jtMdLista = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        nome1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        md1 = new javax.swing.JTextField();
        butao1 = new javax.swing.JButton();
        nome2 = new javax.swing.JTextField();
        md2 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        butao2 = new javax.swing.JButton();
        nome3 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        md3 = new javax.swing.JTextField();
        butao3 = new javax.swing.JButton();
        nome4 = new javax.swing.JTextField();
        md4 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        butao4 = new javax.swing.JButton();
        butao8 = new javax.swing.JButton();
        butao6 = new javax.swing.JButton();
        nome5 = new javax.swing.JTextField();
        nome7 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        md5 = new javax.swing.JTextField();
        md7 = new javax.swing.JTextField();
        butao5 = new javax.swing.JButton();
        butao7 = new javax.swing.JButton();
        nome8 = new javax.swing.JTextField();
        nome6 = new javax.swing.JTextField();
        md8 = new javax.swing.JTextField();
        md6 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        md9 = new javax.swing.JTextField();
        butao9 = new javax.swing.JButton();
        nome10 = new javax.swing.JTextField();
        md10 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        butao10 = new javax.swing.JButton();
        nome9 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        butao13 = new javax.swing.JButton();
        butao11 = new javax.swing.JButton();
        nome12 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        md12 = new javax.swing.JTextField();
        butao12 = new javax.swing.JButton();
        nome13 = new javax.swing.JTextField();
        nome11 = new javax.swing.JTextField();
        md13 = new javax.swing.JTextField();
        md11 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        md14 = new javax.swing.JTextField();
        butao14 = new javax.swing.JButton();
        nome14 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        md15 = new javax.swing.JTextField();
        butao15 = new javax.swing.JButton();
        nome15 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nomeRelacao = new javax.swing.JTextField();
        mdRelacao = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        marcaEnv = new javax.swing.JTextField();
        modeloEnv = new javax.swing.JTextField();
        numEnv = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        perfil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dados do Sistema PAF");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Informações do Sistema PAF");
        jLabel4.setEnabled(false);

        ok.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Comercial");

        jLabel2.setText("Versão");

        jtNomeComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeComercialActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Arquivo da relação dos executáveis - Lista.txt");
        jLabel3.setEnabled(false);

        jLabel5.setText("Nome");

        jLabel6.setText("MD-5");

        jtNomeExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeExeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setText("Principal Arquivo Executável");
        jLabel7.setEnabled(false);

        jLabel8.setText("Nome");

        jLabel9.setText("MD-5");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel41.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel41.setText("Retaguarda / .dll = \"relacaoexe.txt\"");
        jLabel41.setEnabled(false);

        nome1.setEnabled(false);
        nome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome1ActionPerformed(evt);
            }
        });

        jLabel42.setText("Nome");

        jLabel43.setText("MD-5");

        md1.setEnabled(false);

        butao1.setText("ADD/Remove 1");
        butao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao1ActionPerformed(evt);
            }
        });

        nome2.setEnabled(false);
        nome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome2ActionPerformed(evt);
            }
        });

        md2.setEnabled(false);

        jLabel44.setText("MD-5");

        jLabel45.setText("Nome");

        butao2.setText("ADD/Remove 2");
        butao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao2ActionPerformed(evt);
            }
        });

        nome3.setEnabled(false);
        nome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome3ActionPerformed(evt);
            }
        });

        jLabel46.setText("Nome");

        jLabel47.setText("MD-5");

        md3.setEnabled(false);
        md3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md3ActionPerformed(evt);
            }
        });

        butao3.setText("ADD/Remove 3");
        butao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao3ActionPerformed(evt);
            }
        });

        nome4.setEnabled(false);
        nome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome4ActionPerformed(evt);
            }
        });

        md4.setEnabled(false);

        jLabel48.setText("MD-5");

        jLabel49.setText("Nome");

        butao4.setText("ADD/Remove 4");
        butao4.setToolTipText("");
        butao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao4ActionPerformed(evt);
            }
        });

        butao8.setText("ADD/Remove 8");
        butao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao8ActionPerformed(evt);
            }
        });

        butao6.setText("ADD/Remove 6");
        butao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao6ActionPerformed(evt);
            }
        });

        nome5.setEnabled(false);
        nome5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome5ActionPerformed(evt);
            }
        });

        nome7.setEnabled(false);
        nome7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome7ActionPerformed(evt);
            }
        });

        jLabel50.setText("Nome");

        jLabel51.setText("Nome");

        jLabel52.setText("MD-5");

        jLabel53.setText("MD-5");

        md5.setEnabled(false);
        md5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md5ActionPerformed(evt);
            }
        });

        md7.setEnabled(false);

        butao5.setText("ADD/Remove 5");
        butao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao5ActionPerformed(evt);
            }
        });

        butao7.setText("ADD/Remove 7");
        butao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao7ActionPerformed(evt);
            }
        });

        nome8.setEnabled(false);
        nome8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome8ActionPerformed(evt);
            }
        });

        nome6.setEnabled(false);
        nome6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome6ActionPerformed(evt);
            }
        });

        md8.setEnabled(false);

        md6.setEnabled(false);

        jLabel54.setText("MD-5");

        jLabel55.setText("MD-5");

        jLabel56.setText("Nome");

        jLabel57.setText("Nome");

        md9.setEnabled(false);

        butao9.setText("ADD/Remove 9");
        butao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao9ActionPerformed(evt);
            }
        });

        nome10.setEnabled(false);
        nome10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome10ActionPerformed(evt);
            }
        });

        md10.setEnabled(false);

        jLabel58.setText("MD-5");

        jLabel59.setText("Nome");

        butao10.setText("ADD/Remove 10");
        butao10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao10ActionPerformed(evt);
            }
        });

        nome9.setEnabled(false);
        nome9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome9ActionPerformed(evt);
            }
        });

        jLabel60.setText("Nome");

        jLabel61.setText("MD-5");

        jLabel62.setText("Nome");

        jLabel63.setText("MD-5");

        butao13.setText("ADD/Remove 13");
        butao13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao13ActionPerformed(evt);
            }
        });

        butao11.setText("ADD/Remove 11");
        butao11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao11ActionPerformed(evt);
            }
        });

        nome12.setEnabled(false);
        nome12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome12ActionPerformed(evt);
            }
        });

        jLabel64.setText("Nome");

        jLabel65.setText("MD-5");

        md12.setEnabled(false);

        butao12.setText("ADD/Remove 12");
        butao12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao12ActionPerformed(evt);
            }
        });

        nome13.setEnabled(false);
        nome13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome13ActionPerformed(evt);
            }
        });

        nome11.setEnabled(false);
        nome11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome11ActionPerformed(evt);
            }
        });

        md13.setEnabled(false);

        md11.setEnabled(false);

        jLabel66.setText("MD-5");

        jLabel67.setText("MD-5");

        jLabel68.setText("Nome");

        jLabel69.setText("Nome");

        md14.setEnabled(false);

        butao14.setText("ADD/Remove 14");
        butao14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao14ActionPerformed(evt);
            }
        });

        nome14.setEnabled(false);
        nome14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome14ActionPerformed(evt);
            }
        });

        jLabel70.setText("Nome");

        jLabel71.setText("MD-5");

        md15.setEnabled(false);

        butao15.setText("ADD/Remove 15");
        butao15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao15ActionPerformed(evt);
            }
        });

        nome15.setEnabled(false);
        nome15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(md1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome2)
                            .addComponent(md2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butao3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome3)
                            .addComponent(md3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome11)
                                    .addComponent(md11, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome12)
                                    .addComponent(md12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome13)
                                    .addComponent(md13, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome14)
                                    .addComponent(md14, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butao15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome15)
                            .addComponent(md15, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butao4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome4)
                            .addComponent(md4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butao9)
                                    .addComponent(butao10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nome9)
                                            .addComponent(md9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nome10)
                                            .addComponent(md10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome5)
                                    .addComponent(md5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome6)
                                    .addComponent(md6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome7)
                                    .addComponent(md7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome8)
                                    .addComponent(md8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(md1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(nome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(nome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47))))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(nome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(nome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel57)
                            .addComponent(nome6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(nome7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(nome8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54))))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nome9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(md9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(butao10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nome10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(md10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel69))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao12))
                    .addComponent(jLabel64)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nome12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel65))))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao13))
                    .addComponent(jLabel68)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nome13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel66))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(butao14))
                    .addComponent(jLabel62)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nome14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel63))))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nome15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(md15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel70)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel71))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(butao15))))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setText("Informações do arquivo \"relacaoexe.txt\"");
        jLabel10.setEnabled(false);

        jLabel11.setText("Nome");

        jLabel12.setText("MD-5");

        nomeRelacao.setText("relacaoexe.txt");

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel13.setText("Informações do evelope");
        jLabel13.setEnabled(false);

        jLabel14.setText("Marca");

        jLabel15.setText("Modelo");

        jLabel16.setText("Número");

        marcaEnv.setText("ELC BRASIL");
        marcaEnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaEnvActionPerformed(evt);
            }
        });

        modeloEnv.setText("SLML 31");

        jLabel17.setText("Perfis de Requisitos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel9)
                        .addGap(211, 211, 211)
                        .addComponent(jLabel14)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(nomeRelacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(mdRelacao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel11)
                                        .addGap(117, 117, 117)
                                        .addComponent(jLabel12)))
                                .addGap(120, 120, 120)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jtNomeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jtMdLista, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtNomeComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5)
                                .addGap(166, 166, 166)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jtNomeExe, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jtMdExe, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(marcaEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(modeloEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(numEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNomeComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNomeExe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtMdExe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtNomeLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMdLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel17))
                    .addComponent(perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeRelacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mdRelacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        if ("".equals(jtNomeComercial.getText()) || "".equals(jtVersao.getText()) || "".equals(jtNomeExe.getText())
                || "".equals(jtMdExe.getText()) || "".equals(jtNomeLista.getText()) || "".equals(jtMdLista.getText())
                || "".equals(nomeRelacao.getText()) || "".equals(mdRelacao.getText()) || "".equals(marcaEnv.getText())
                || "".equals(modeloEnv.getText()) || "".equals(numEnv.getText()) || "".equals(perfil.getText())) {
            JOptionPane.showMessageDialog(null, "EXISTE(M) CAMPO(S) EM BRANCO(S)!", "Aviso de erro!!!", JOptionPane.PLAIN_MESSAGE);
        } else {
            nomeComercial = CorretorOrtografico.corretor(jtNomeComercial.getText());

            String correto;

            XML.setNomeComercial(jtNomeComercial.getText());
            XML.setVersao(jtVersao.getText());
            XML.setNomeExe(jtNomeExe.getText());
            XML.setMdExe(jtMdExe.getText());
            XML.setNomeLista(jtNomeLista.getText());
            XML.setMdLista(jtMdLista.getText());

            if (edit1 == true) {
                correto = CorretorOrtografico.corretor(md1.getText());
                XML.setMd1(correto);
                correto = CorretorOrtografico.corretor(nome1.getText());
                XML.setNome1(correto);
            }

            if (edit2 == true) {
                correto = CorretorOrtografico.corretor(md2.getText());
                XML.setMd2(correto);
                correto = CorretorOrtografico.corretor(nome2.getText());
                XML.setNome2(correto);
            }

            if (edit3 == true) {
                correto = CorretorOrtografico.corretor(md3.getText());
                XML.setMd3(correto);
                correto = CorretorOrtografico.corretor(nome3.getText());
                XML.setNome3(correto);
            }

            if (edit4 == true) {
                correto = CorretorOrtografico.corretor(md4.getText());
                XML.setMd4(correto);
                correto = CorretorOrtografico.corretor(nome4.getText());
                XML.setNome4(correto);
            }

            if (edit5 == true) {
                correto = CorretorOrtografico.corretor(md5.getText());
                XML.setMd5(correto);
                correto = CorretorOrtografico.corretor(nome5.getText());
                XML.setNome5(correto);
            }

            if (edit6 == true) {
                correto = CorretorOrtografico.corretor(md6.getText());
                XML.setMd6(correto);
                correto = CorretorOrtografico.corretor(nome6.getText());
                XML.setNome6(correto);
            }

            if (edit7 == true) {
                correto = CorretorOrtografico.corretor(md7.getText());
                XML.setMd7(correto);
                correto = CorretorOrtografico.corretor(nome7.getText());
                XML.setNome7(correto);
            }

            if (edit8 == true) {
                correto = CorretorOrtografico.corretor(md8.getText());
                XML.setMd8(correto);
                correto = CorretorOrtografico.corretor(nome8.getText());
                XML.setNome8(correto);
            }

            if (edit9 == true) {
                correto = CorretorOrtografico.corretor(md9.getText());
                XML.setMd9(correto);
                correto = CorretorOrtografico.corretor(nome9.getText());
                XML.setNome9(correto);
            }

            if (edit10 == true) {
                correto = CorretorOrtografico.corretor(md10.getText());
                XML.setMd10(correto);
                correto = CorretorOrtografico.corretor(nome10.getText());
                XML.setNome10(correto);
            }

            if (edit11 == true) {
                correto = CorretorOrtografico.corretor(md11.getText());
                XML.setMd11(correto);
                correto = CorretorOrtografico.corretor(nome11.getText());
                XML.setNome11(correto);
            }

            if (edit12 == true) {
                correto = CorretorOrtografico.corretor(md12.getText());
                XML.setMd12(correto);
                correto = CorretorOrtografico.corretor(nome12.getText());
                XML.setNome12(correto);
            }

            if (edit13 == true) {
                correto = CorretorOrtografico.corretor(md13.getText());
                XML.setMd13(correto);
                correto = CorretorOrtografico.corretor(nome13.getText());
                XML.setNome13(correto);
            }

            if (edit14 == true) {
                correto = CorretorOrtografico.corretor(md14.getText());
                XML.setMd14(correto);
                correto = CorretorOrtografico.corretor(nome14.getText());
                XML.setNome14(correto);
            }

            if (edit15 == true) {
                correto = CorretorOrtografico.corretor(md15.getText());
                XML.setMd15(correto);
                correto = CorretorOrtografico.corretor(nome15.getText());
                XML.setNome15(correto);
            }

            correto = CorretorOrtografico.corretor(nomeRelacao.getText());
            XML.setNomeRelacao(correto)
                    ;
            correto = CorretorOrtografico.corretor(mdRelacao.getText());
            XML.setMdRelacao(correto);
            
            correto = CorretorOrtografico.corretor(marcaEnv.getText());
            XML.setMarcaEnv(correto);
            
            correto = CorretorOrtografico.corretor(modeloEnv.getText());
            XML.setModeloEnv(correto);
            
            correto = CorretorOrtografico.corretor(numEnv.getText());
            XML.setNumEnv(correto);
            
            correto = CorretorOrtografico.corretor(perfil.getText());
            XML.setPerfil(correto);

            D_IdentificacaoPAF.setFlag(true);
            dispose();
        }
    }//GEN-LAST:event_okActionPerformed

    private void jtNomeExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeExeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeExeActionPerformed

    private void nome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome1ActionPerformed

    private void butao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao1ActionPerformed

        if (edit1 == false) {
            edit1 = true;
            md1.setEnabled(true);
            nome1.setEnabled(true);
        } else {
            edit1 = false;
            md1.setEnabled(false);
            md1.setText("");
            nome1.setEnabled(false);
            nome1.setText("");
        }
    }//GEN-LAST:event_butao1ActionPerformed

    private void nome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome2ActionPerformed

    private void butao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao2ActionPerformed

        if (edit2 == false) {
            edit2 = true;
            md2.setEnabled(true);
            nome2.setEnabled(true);
        } else {
            edit2 = false;
            md2.setEnabled(false);
            md2.setText("");
            nome2.setEnabled(false);
            nome2.setText("");
        }
    }//GEN-LAST:event_butao2ActionPerformed

    private void nome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome3ActionPerformed

    private void butao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao3ActionPerformed
        if (edit3 == false) {
            edit3 = true;
            md3.setEnabled(true);
            nome3.setEnabled(true);
        } else {
            edit3 = false;
            md3.setEnabled(false);
            md3.setText("");
            nome3.setEnabled(false);
            nome3.setText("");
        }
    }//GEN-LAST:event_butao3ActionPerformed

    private void nome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome4ActionPerformed

    private void butao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao4ActionPerformed
        if (edit4 == false) {
            edit4 = true;
            md4.setEnabled(true);
            nome4.setEnabled(true);
        } else {
            edit4 = false;
            md4.setEnabled(false);
            md4.setText("");
            nome4.setEnabled(false);
            nome4.setText("");
        }
    }//GEN-LAST:event_butao4ActionPerformed

    private void butao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao8ActionPerformed
        if (edit8 == false) {
            edit8 = true;
            md8.setEnabled(true);
            nome8.setEnabled(true);
        } else {
            edit8 = false;
            md8.setEnabled(false);
            md8.setText("");
            nome8.setEnabled(false);
            nome8.setText("");
        }
    }//GEN-LAST:event_butao8ActionPerformed

    private void butao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao6ActionPerformed
        if (edit6 == false) {
            edit6 = true;
            md6.setEnabled(true);
            nome6.setEnabled(true);
        } else {
            edit6 = false;
            md6.setEnabled(false);
            md6.setText("");
            nome6.setEnabled(false);
            nome6.setText("");
        }
    }//GEN-LAST:event_butao6ActionPerformed

    private void nome5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome5ActionPerformed

    private void nome7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome7ActionPerformed

    private void butao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao5ActionPerformed
        if (edit5 == false) {
            edit5 = true;
            md5.setEnabled(true);
            nome5.setEnabled(true);
        } else {
            edit5 = false;
            md5.setEnabled(false);
            md5.setText("");
            nome5.setEnabled(false);
            nome5.setText("");
        }
    }//GEN-LAST:event_butao5ActionPerformed

    private void butao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao7ActionPerformed
        if (edit7 == false) {
            edit7 = true;
            md7.setEnabled(true);
            nome7.setEnabled(true);
        } else {
            edit7 = false;
            md7.setEnabled(false);
            md7.setText("");
            nome7.setEnabled(false);
            nome7.setText("");
        }
    }//GEN-LAST:event_butao7ActionPerformed

    private void nome8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome8ActionPerformed

    private void nome6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome6ActionPerformed

    private void butao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao9ActionPerformed
        if (edit9 == false) {
            edit9 = true;
            md9.setEnabled(true);
            nome9.setEnabled(true);
        } else {
            edit9 = false;
            md9.setEnabled(false);
            md9.setText("");
            nome9.setEnabled(false);
            nome9.setText("");
        }
    }//GEN-LAST:event_butao9ActionPerformed

    private void nome10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome10ActionPerformed

    private void butao10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao10ActionPerformed
        if (edit10 == false) {
            edit10 = true;
            md10.setEnabled(true);
            nome10.setEnabled(true);
        } else {
            edit10 = false;
            md10.setEnabled(false);
            md10.setText("");
            nome10.setEnabled(false);
            nome10.setText("");
        }
    }//GEN-LAST:event_butao10ActionPerformed

    private void nome9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome9ActionPerformed

    private void butao13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao13ActionPerformed
        if (edit13 == false) {
            edit13 = true;
            md13.setEnabled(true);
            nome13.setEnabled(true);
        } else {
            edit13 = false;
            md13.setEnabled(false);
            md13.setText("");
            nome13.setEnabled(false);
            nome13.setText("");
        }
    }//GEN-LAST:event_butao13ActionPerformed

    private void butao11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao11ActionPerformed
        if (edit11 == false) {
            edit11 = true;
            md11.setEnabled(true);
            nome11.setEnabled(true);
        } else {
            edit11 = false;
            md11.setEnabled(false);
            md11.setText("");
            nome11.setEnabled(false);
            nome11.setText("");
        }
    }//GEN-LAST:event_butao11ActionPerformed

    private void nome12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome12ActionPerformed

    private void butao12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao12ActionPerformed
        if (edit12 == false) {
            edit12 = true;
            md12.setEnabled(true);
            nome12.setEnabled(true);
        } else {
            edit12 = false;
            md12.setEnabled(false);
            md12.setText("");
            nome12.setEnabled(false);
            nome12.setText("");
        }
    }//GEN-LAST:event_butao12ActionPerformed

    private void nome13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome13ActionPerformed

    private void nome11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome11ActionPerformed

    private void butao14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao14ActionPerformed
        if (edit14 == false) {
            edit14 = true;
            md14.setEnabled(true);
            nome14.setEnabled(true);
        } else {
            edit14 = false;
            md14.setEnabled(false);
            md14.setText("");
            nome14.setEnabled(false);
            nome14.setText("");
        }
    }//GEN-LAST:event_butao14ActionPerformed

    private void nome14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome14ActionPerformed

    private void butao15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao15ActionPerformed
        if (edit15 == false) {
            edit15 = true;
            md15.setEnabled(true);
            nome15.setEnabled(true);
        } else {
            edit15 = false;
            md15.setEnabled(false);
            md15.setText("");
            nome15.setEnabled(false);
            nome15.setText("");
        }
    }//GEN-LAST:event_butao15ActionPerformed

    private void nome15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome15ActionPerformed

    private void md5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_md5ActionPerformed

    private void md3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_md3ActionPerformed

    private void marcaEnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaEnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaEnvActionPerformed

    private void jtNomeComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeComercialActionPerformed

    public static void setFlag(boolean flag) {
        D_IdentificacaoPAF.flag = flag;
    }

    public static boolean getFlag() {
        return D_IdentificacaoPAF.flag == true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_IdentificacaoPAF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_IdentificacaoPAF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_IdentificacaoPAF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_IdentificacaoPAF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D_IdentificacaoPAF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butao1;
    private javax.swing.JButton butao10;
    private javax.swing.JButton butao11;
    private javax.swing.JButton butao12;
    private javax.swing.JButton butao13;
    private javax.swing.JButton butao14;
    private javax.swing.JButton butao15;
    private javax.swing.JButton butao2;
    private javax.swing.JButton butao3;
    private javax.swing.JButton butao4;
    private javax.swing.JButton butao5;
    private javax.swing.JButton butao6;
    private javax.swing.JButton butao7;
    private javax.swing.JButton butao8;
    private javax.swing.JButton butao9;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtMdExe;
    private javax.swing.JTextField jtMdLista;
    private javax.swing.JTextField jtNomeComercial;
    private javax.swing.JTextField jtNomeExe;
    private javax.swing.JTextField jtNomeLista;
    private javax.swing.JTextField jtVersao;
    private javax.swing.JTextField marcaEnv;
    private javax.swing.JTextField md1;
    private javax.swing.JTextField md10;
    private javax.swing.JTextField md11;
    private javax.swing.JTextField md12;
    private javax.swing.JTextField md13;
    private javax.swing.JTextField md14;
    private javax.swing.JTextField md15;
    private javax.swing.JTextField md2;
    private javax.swing.JTextField md3;
    private javax.swing.JTextField md4;
    private javax.swing.JTextField md5;
    private javax.swing.JTextField md6;
    private javax.swing.JTextField md7;
    private javax.swing.JTextField md8;
    private javax.swing.JTextField md9;
    private javax.swing.JTextField mdRelacao;
    private javax.swing.JTextField modeloEnv;
    private javax.swing.JTextField nome1;
    private javax.swing.JTextField nome10;
    private javax.swing.JTextField nome11;
    private javax.swing.JTextField nome12;
    private javax.swing.JTextField nome13;
    private javax.swing.JTextField nome14;
    private javax.swing.JTextField nome15;
    private javax.swing.JTextField nome2;
    private javax.swing.JTextField nome3;
    private javax.swing.JTextField nome4;
    private javax.swing.JTextField nome5;
    private javax.swing.JTextField nome6;
    private javax.swing.JTextField nome7;
    private javax.swing.JTextField nome8;
    private javax.swing.JTextField nome9;
    private javax.swing.JTextField nomeRelacao;
    private javax.swing.JTextField numEnv;
    private javax.swing.JButton ok;
    private javax.swing.JTextField perfil;
    // End of variables declaration//GEN-END:variables
}
