package Interface;

import geradorxml.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Hiago
 */
public class E_CaracteristicasPAF extends javax.swing.JFrame {

    static boolean flag = false;
    static int tipoDesenvolvimento = 0, tipoFuncionamento = 0, gerarArquivo = 0, integracaoPAF = 0, interrupcao = 0;
    static boolean impressao1 = false, impressao2 = false, impressao3 = false,
            impressao4 = false, impressao5 = false, impressao6 = false, impressao7 = false;

    public static int getInterrupcao() {
        return interrupcao;
    }

    public static int getTipoDesenvolvimento() {
        return tipoDesenvolvimento;
    }

    public static boolean isImpressao7() {
        return impressao7;
    }

    public E_CaracteristicasPAF() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        buttonGroup1.add(jbA1);
        buttonGroup1.add(jbA2);
        buttonGroup1.add(jbA3);

        buttonGroup2.add(jbB1);
        buttonGroup2.add(jbB2);
        buttonGroup2.add(jbB3);

        buttonGroup3.add(jbC1);
        buttonGroup3.add(jbC2);
        buttonGroup3.add(jbC3);

        buttonGroup4.add(jbD1);
        buttonGroup4.add(jbD2);
        buttonGroup4.add(jbD3);
        buttonGroup4.add(jbD4);

        buttonGroup5.add(jbF1);
        buttonGroup5.add(jbF2);
        buttonGroup5.add(jbF3);
    }

    public static boolean isImpressao1() {
        return impressao1;
    }

    public static boolean isImpressao2() {
        return impressao2;
    }

    public static boolean isImpressao3() {
        return impressao3;
    }

    public static boolean isImpressao4() {
        return impressao4;
    }

    public static boolean isImpressao5() {
        return impressao5;
    }

    public static boolean isImpressao6() {
        return impressao6;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        linguagem = new javax.swing.JTextField();
        so = new javax.swing.JTextField();
        bd = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jbA1 = new javax.swing.JRadioButton();
        jbA2 = new javax.swing.JRadioButton();
        jbA3 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jbB1 = new javax.swing.JRadioButton();
        jbB2 = new javax.swing.JRadioButton();
        jbB3 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jbC1 = new javax.swing.JRadioButton();
        jbC3 = new javax.swing.JRadioButton();
        jbC2 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jbD1 = new javax.swing.JRadioButton();
        jbD2 = new javax.swing.JRadioButton();
        jbD4 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jbE1 = new javax.swing.JRadioButton();
        jbE2 = new javax.swing.JRadioButton();
        jbE3 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jbF3 = new javax.swing.JRadioButton();
        jbF1 = new javax.swing.JRadioButton();
        jbF2 = new javax.swing.JRadioButton();
        jbD3 = new javax.swing.JRadioButton();
        jbE4 = new javax.swing.JRadioButton();
        jbE5 = new javax.swing.JRadioButton();
        jbE7 = new javax.swing.JRadioButton();
        jbE6 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Características do sistema PAF");

        jLabel1.setText("Linguagem de Programação");

        jLabel2.setText("Sistema Operacional");

        jLabel3.setText("Banco de dados");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Características do PAF");
        jLabel4.setEnabled(false);

        linguagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linguagemActionPerformed(evt);
            }
        });

        so.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soActionPerformed(evt);
            }
        });

        ok.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel16.setText("Tipo de Desenvolvimento");

        jbA1.setText("Comercializável");
        jbA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbA1ActionPerformed(evt);
            }
        });

        jbA2.setText("Exclusivo Próprio");
        jbA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbA2ActionPerformed(evt);
            }
        });

        jbA3.setText("Exclusivo Terceirizado");
        jbA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbA3ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel17.setText("Tipo de Funcionamento");

        jbB1.setText("Exclusivamente \"Stand-Alone\"");
        jbB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbB1ActionPerformed(evt);
            }
        });

        jbB2.setText("Em Rede");
        jbB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbB2ActionPerformed(evt);
            }
        });

        jbB3.setText("Parametrizável");
        jbB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbB3ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel18.setText("Meio de Geração do Sped/Sintegra");

        jbC1.setText("Pelo PAF-ECF");
        jbC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC1ActionPerformed(evt);
            }
        });

        jbC3.setText("Pelo Sistema PED ou EFD");
        jbC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC3ActionPerformed(evt);
            }
        });

        jbC2.setText("Pelo Sistema de Retaguarda");
        jbC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel19.setText("Integração do PAF");

        jbD1.setText("Com sistema de Retaguarda");
        jbD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbD1ActionPerformed(evt);
            }
        });

        jbD2.setText("Com sistema PED");
        jbD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbD2ActionPerformed(evt);
            }
        });

        jbD4.setText("Não Integrado");
        jbD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbD4ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel20.setText("Forma de impressão no CF");

        jbE1.setText("Concomitante");
        jbE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbE1ActionPerformed(evt);
            }
        });

        jbE2.setText("Não Concomitante, C/ emissão de DAV");
        jbE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbE2ActionPerformed(evt);
            }
        });

        jbE3.setText("Não Concomitante, C/ Controle de pré-venda");
        jbE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbE3ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel21.setText("Tratamento de interrupção");

        jbF3.setText("Bloqueio de Funções");
        jbF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbF3ActionPerformed(evt);
            }
        });

        jbF1.setText("Recuperação de Dados");
        jbF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbF1ActionPerformed(evt);
            }
        });

        jbF2.setText("Cancelamento Automático");
        jbF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbF2ActionPerformed(evt);
            }
        });

        jbD3.setText("Com Ambos");
        jbD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbD3ActionPerformed(evt);
            }
        });

        jbE4.setText("Não Concomitante, C/ Controle de conta de cliente");
        jbE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbE4ActionPerformed(evt);
            }
        });

        jbE5.setText("DAV emitido sem possibilidade de impressão");
        jbE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbE5ActionPerformed(evt);
            }
        });

        jbE7.setText("DAV impresso em ECF");
        jbE7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbE7ActionPerformed(evt);
            }
        });

        jbE6.setText("DAV impresso em impressora não fiscal");
        jbE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbE6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(linguagem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(so, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jbA1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbA2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbA3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbD1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbD2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbD3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbD4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbB1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(jbC1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbB2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(240, 240, 240)
                                .addComponent(jbC2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbB3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210)
                                .addComponent(jbC3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbE5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbE6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbE7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbE1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbE2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbE3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbE4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbF1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbF2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbF3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jbB1)
                            .addComponent(jbC1))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(linguagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbB2)
                                    .addComponent(jbC2))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbB3)
                            .addComponent(jbC3))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(so, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel3)
                                        .addGap(4, 4, 4)
                                        .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbF1)
                                        .addGap(12, 12, 12)
                                        .addComponent(jbF2)))
                                .addGap(18, 18, 18)
                                .addComponent(jbF3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbE1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbE2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbE3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbE4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbE5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(11, 11, 11)
                        .addComponent(jbA1)
                        .addGap(12, 12, 12)
                        .addComponent(jbA2)
                        .addGap(12, 12, 12)
                        .addComponent(jbA3)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel19)
                        .addGap(17, 17, 17)
                        .addComponent(jbD1)
                        .addGap(7, 7, 7)
                        .addComponent(jbD2)
                        .addGap(7, 7, 7)
                        .addComponent(jbD3)
                        .addGap(7, 7, 7)
                        .addComponent(jbD4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbE6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbE7)
                .addGap(89, 89, 89)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linguagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linguagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linguagemActionPerformed

    private void soActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        if (tipoDesenvolvimento == 0 || tipoFuncionamento == 0 || gerarArquivo == 0 || integracaoPAF == 0 || interrupcao == 0
                || "".equals(linguagem.getText()) || "".equals(so.getText()) || "".equals(bd.getText()) || (impressao1 == false
                && impressao2 == false && impressao3 == false && impressao4 == false && impressao5 == false && impressao6 == false
                && impressao7 == false)) {
            JOptionPane.showMessageDialog(null, "EXISTE(M) CAMPO(S) EM BRANCO(S)!", "Aviso de erro!!!", JOptionPane.PLAIN_MESSAGE);
        } else {
            
            XML.setTipoDesenvolvimento(tipoDesenvolvimento);
            XML.setTipoFuncionamento(tipoFuncionamento);
            XML.setGerarArquivo(gerarArquivo);
            XML.setIntegracaoPAF(integracaoPAF);
            XML.setInterrupcao(interrupcao);
            
            String correto;
            
            correto = CorretorOrtografico.corretor(linguagem.getText());
            XML.setLinguagem(correto);
            
            correto = CorretorOrtografico.corretor(so.getText());
            XML.setSo(correto);
            
            correto = CorretorOrtografico.corretor(bd.getText());
            XML.setBd(correto);

            E_CaracteristicasPAF.setFlag(true);
            dispose();
        }
    }//GEN-LAST:event_okActionPerformed

    private void jbA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbA1ActionPerformed
        tipoDesenvolvimento = 1;
    }//GEN-LAST:event_jbA1ActionPerformed

    private void jbA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbA2ActionPerformed
        tipoDesenvolvimento = 2;
    }//GEN-LAST:event_jbA2ActionPerformed

    private void jbB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbB1ActionPerformed
        tipoFuncionamento = 1;
    }//GEN-LAST:event_jbB1ActionPerformed

    private void jbB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbB2ActionPerformed
        tipoFuncionamento = 2;
    }//GEN-LAST:event_jbB2ActionPerformed

    private void jbC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC3ActionPerformed
        gerarArquivo = 3;
    }//GEN-LAST:event_jbC3ActionPerformed

    private void jbC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC2ActionPerformed
        gerarArquivo = 2;
    }//GEN-LAST:event_jbC2ActionPerformed

    private void jbD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbD1ActionPerformed
        integracaoPAF = 1;
    }//GEN-LAST:event_jbD1ActionPerformed

    private void jbD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbD2ActionPerformed
        integracaoPAF = 2;
    }//GEN-LAST:event_jbD2ActionPerformed

    private void jbE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbE1ActionPerformed
        if (impressao1 == false) {
            impressao1 = true;
        } else {
            impressao1 = false;
        }
    }//GEN-LAST:event_jbE1ActionPerformed

    private void jbE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbE2ActionPerformed
        if (impressao2 == false) {
            impressao2 = true;
        } else {
            impressao2 = false;
        }
    }//GEN-LAST:event_jbE2ActionPerformed

    private void jbF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbF1ActionPerformed
        interrupcao = 1;
    }//GEN-LAST:event_jbF1ActionPerformed

    private void jbF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbF2ActionPerformed
        interrupcao = 2;
    }//GEN-LAST:event_jbF2ActionPerformed

    private void jbE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbE4ActionPerformed
        if (impressao4 == false) {
            impressao4 = true;
        } else {
            impressao4 = false;
        }
    }//GEN-LAST:event_jbE4ActionPerformed

    private void jbE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbE5ActionPerformed
        if (impressao5 == false) {
            impressao5 = true;
        } else {
            impressao5 = false;
        }
    }//GEN-LAST:event_jbE5ActionPerformed

    private void jbF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbF3ActionPerformed
        interrupcao = 3;
    }//GEN-LAST:event_jbF3ActionPerformed

    private void jbA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbA3ActionPerformed
        tipoDesenvolvimento = 3;
    }//GEN-LAST:event_jbA3ActionPerformed

    private void jbB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbB3ActionPerformed
        tipoFuncionamento = 3;
    }//GEN-LAST:event_jbB3ActionPerformed

    private void jbC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC1ActionPerformed
        gerarArquivo = 1;
    }//GEN-LAST:event_jbC1ActionPerformed

    private void jbD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbD3ActionPerformed
        integracaoPAF = 3;
    }//GEN-LAST:event_jbD3ActionPerformed

    private void jbD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbD4ActionPerformed
        integracaoPAF = 4;
    }//GEN-LAST:event_jbD4ActionPerformed

    private void jbE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbE3ActionPerformed
        if (impressao3 == false) {
            impressao3 = true;
        } else {
            impressao3 = false;
        }
    }//GEN-LAST:event_jbE3ActionPerformed

    private void jbE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbE6ActionPerformed
        if (impressao6 == false) {
            impressao6 = true;
        } else {
            impressao6 = false;
        }
    }//GEN-LAST:event_jbE6ActionPerformed

    private void jbE7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbE7ActionPerformed
        if (impressao7 == false) {
            impressao7 = true;
        } else {
            impressao7 = false;
        }
    }//GEN-LAST:event_jbE7ActionPerformed

    public static void setFlag(boolean flag) {
        E_CaracteristicasPAF.flag = flag;
    }

    public static boolean getFlag() {
        return E_CaracteristicasPAF.flag == true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_CaracteristicasPAF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_CaracteristicasPAF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_CaracteristicasPAF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_CaracteristicasPAF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_CaracteristicasPAF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jbA1;
    private javax.swing.JRadioButton jbA2;
    private javax.swing.JRadioButton jbA3;
    private javax.swing.JRadioButton jbB1;
    private javax.swing.JRadioButton jbB2;
    private javax.swing.JRadioButton jbB3;
    private javax.swing.JRadioButton jbC1;
    private javax.swing.JRadioButton jbC2;
    private javax.swing.JRadioButton jbC3;
    private javax.swing.JRadioButton jbD1;
    private javax.swing.JRadioButton jbD2;
    private javax.swing.JRadioButton jbD3;
    private javax.swing.JRadioButton jbD4;
    private javax.swing.JRadioButton jbE1;
    private javax.swing.JRadioButton jbE2;
    private javax.swing.JRadioButton jbE3;
    private javax.swing.JRadioButton jbE4;
    private javax.swing.JRadioButton jbE5;
    private javax.swing.JRadioButton jbE6;
    private javax.swing.JRadioButton jbE7;
    private javax.swing.JRadioButton jbF1;
    private javax.swing.JRadioButton jbF2;
    private javax.swing.JRadioButton jbF3;
    private javax.swing.JTextField linguagem;
    private javax.swing.JButton ok;
    private javax.swing.JTextField so;
    // End of variables declaration//GEN-END:variables
}
