/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import geradorxml.CorretorOrtografico;
import geradorxml.XML;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Hiago
 */
public class N_Final extends javax.swing.JFrame {

    static boolean flag = false;
    static String diaAtual, mesAtual, anoAtual, local;
    static int gerente = 0, aprovacao = 0;
    static boolean controlHiago = false, controlPaulo = false, controlOutroGerente = false;
    static boolean controlEdmundo = false, controlMarcelo = false, controlOutroAprovacao = false,
            controlJuliana = false, controlTaciana = false;
    static String nomeG, cpfG, nomeA, cpfA;

    public static String getNomeGerente() {
        return nomeG;
    }

    public static String getCPFGerente() {
        return cpfG;
    }

    public static String getNomeAprovacao() {
        return nomeA;
    }

    public static String getCPFAprovacao() {
        return cpfA;
    }

    public static void setDiaAtual(String diaAtual) {
        N_Final.diaAtual = diaAtual;
    }

    public static int getGerente() {
        return gerente;
    }

    public static int getAprovacao() {
        return aprovacao;
    }

    public static void setGerente(int gerente) {
        N_Final.gerente = gerente;
    }

    public static String getLocal() {
        return local;
    }

    public static void setLocal(String local) {
        N_Final.local = local;
    }

    public static void setMesAtual(String mesAtual) {
        N_Final.mesAtual = mesAtual;
    }

    public static void setAnoAtual(String anoAtual) {
        N_Final.anoAtual = anoAtual;
    }

    public static String getDiaAtual() {
        return diaAtual;
    }

    public static String getMesAtual() {
        return mesAtual;
    }

    public static String getAnoAtual() {
        return anoAtual;
    }

    public static void setFlag(boolean flag) {
        N_Final.flag = flag;
    }

    public static boolean isFlag() {
        return flag;
    }

    public N_Final() {
        initComponents();
        this.setLocationRelativeTo(null);

        jTDia.setText(N_Final.getDay());
        jTMes.setText(N_Final.getMonth());
        jTAno.setText(N_Final.getYear());

        buttonGroup1.add(hiago);
        buttonGroup1.add(paulo);
        buttonGroup1.add(outroGerente);

        buttonGroup2.add(edmundo);
        buttonGroup2.add(marcelo);
        buttonGroup2.add(juliana);
        buttonGroup2.add(taciana);
        buttonGroup2.add(outroAprovacao);

        this.setVisible(true);
    }

    private static String getDay() {
        DateFormat dateFormat = new SimpleDateFormat("dd");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private static String getMonth() {
        DateFormat dateFormat = new SimpleDateFormat("MM");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private static String getYear() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy");
        Date date = new Date();
        return dateFormat.format(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTDia = new javax.swing.JTextField();
        jTMes = new javax.swing.JTextField();
        jTAno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTlocal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hiago = new javax.swing.JRadioButton();
        paulo = new javax.swing.JRadioButton();
        outroGerente = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nomeGerente = new javax.swing.JTextField();
        cpfGerente = new javax.swing.JTextField();
        edmundo = new javax.swing.JRadioButton();
        marcelo = new javax.swing.JRadioButton();
        outroAprovacao = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nomeAprovacao = new javax.swing.JTextField();
        cpfAprovacao = new javax.swing.JTextField();
        juliana = new javax.swing.JRadioButton();
        taciana = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finalização do Laudo");

        ok.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Local e Data");
        jLabel1.setEnabled(false);

        jLabel2.setText("Dia");

        jLabel3.setText("Mês");

        jLabel4.setText("Ano");

        jLabel5.setText("Local");

        jTlocal.setText("Goiania, GO");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Gerente de Teste");
        jLabel6.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setText("Aprovação do Relatório - Coordenador");
        jLabel7.setEnabled(false);

        hiago.setText("Hiago");
        hiago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiagoActionPerformed(evt);
            }
        });

        paulo.setText("Paulo");
        paulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauloActionPerformed(evt);
            }
        });

        outroGerente.setText("Outro");
        outroGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outroGerenteActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome");

        jLabel9.setText("CPF");

        nomeGerente.setEnabled(false);

        cpfGerente.setEnabled(false);

        edmundo.setText("Edmundo");
        edmundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edmundoActionPerformed(evt);
            }
        });

        marcelo.setText("Marcelo");
        marcelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marceloActionPerformed(evt);
            }
        });

        outroAprovacao.setText("Outro");
        outroAprovacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outroAprovacaoActionPerformed(evt);
            }
        });

        jLabel10.setText("Nome");

        jLabel11.setText("CPF");

        nomeAprovacao.setEnabled(false);

        cpfAprovacao.setEnabled(false);

        juliana.setText("Juliana");
        juliana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                julianaActionPerformed(evt);
            }
        });

        taciana.setText("Taciana");
        taciana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacianaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel4)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTDia, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jTMes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTAno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jTlocal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(hiago)
                            .addGap(63, 63, 63)
                            .addComponent(paulo)
                            .addGap(63, 63, 63)
                            .addComponent(outroGerente)
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(17, 17, 17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cpfGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(edmundo)
                                        .addComponent(juliana))
                                    .addGap(63, 63, 63)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(marcelo)
                                        .addComponent(taciana))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(outroAprovacao)
                                    .addGap(13, 13, 13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addGap(17, 17, 17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomeAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cpfAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTlocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cpfGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hiago)
                            .addComponent(paulo)
                            .addComponent(outroGerente))))
                .addGap(10, 10, 10)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edmundo)
                    .addComponent(marcelo))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cpfAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(outroAprovacao)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juliana)
                    .addComponent(taciana))
                .addGap(88, 88, 88)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        if ("".equals(jTDia.getText()) || "".equals(jTMes.getText()) || "".equals(jTAno.getText()) || "".equals(jTlocal.getText())
                || (controlOutroGerente == false && controlHiago == false && controlPaulo == false)
                || (controlOutroGerente == true && ("".equals(nomeGerente.getText()) || "".equals(cpfGerente.getText())))
                || (controlOutroAprovacao == false && controlEdmundo == false && controlMarcelo == false && controlTaciana == false && controlJuliana == false)
                || (controlOutroAprovacao == true && ("".equals(nomeAprovacao.getText()) || "".equals(cpfAprovacao.getText())))) {
            JOptionPane.showMessageDialog(null, "EXISTE(M) CAMPO(S) EM BRANCO(S)!", "Aviso de erro!!!", JOptionPane.PLAIN_MESSAGE);
        } else {

            String correto;

            correto = CorretorOrtografico.corretor(jTDia.getText());
            N_Final.setDiaAtual(correto);
            
            correto = CorretorOrtografico.corretor(jTMes.getText());
            N_Final.setMesAtual(correto);
            
            correto = CorretorOrtografico.corretor(jTAno.getText());
            N_Final.setAnoAtual(correto);
            
            correto = CorretorOrtografico.corretor(jTlocal.getText());
            N_Final.setLocal(correto);
            
            nomeG = CorretorOrtografico.corretor(nomeGerente.getText());
            cpfG = cpfGerente.getText();

            nomeA = CorretorOrtografico.corretor(nomeAprovacao.getText());
            cpfA = cpfAprovacao.getText();

            XML.setDiaAtual(diaAtual);
            XML.setMesAtual(mesAtual);
            XML.setAnoAtual(anoAtual);
            
            correto = CorretorOrtografico.corretor(local);
            XML.setLocal(correto);

            XML.setGerente(gerente);
            XML.setAprovacao(aprovacao);

            N_Final.setFlag(true);
            dispose();
        }
    }//GEN-LAST:event_okActionPerformed

    private void hiagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiagoActionPerformed
        controlHiago = true;
        controlPaulo = false;
        controlOutroGerente = false;
        if (gerente == 3) {
            controlOutroGerente = false;
            nomeGerente.setEnabled(false);
            nomeGerente.setText("");
            cpfGerente.setEnabled(false);
            cpfGerente.setText("");
        }
        gerente = 1;
    }//GEN-LAST:event_hiagoActionPerformed

    private void pauloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauloActionPerformed
        controlHiago = false;
        controlPaulo = true;
        controlOutroGerente = false;
        if (gerente == 3) {
            nomeGerente.setEnabled(false);
            nomeGerente.setText("");
            cpfGerente.setEnabled(false);
            cpfGerente.setText("");
            controlOutroGerente = false;
        }
        gerente = 2;
    }//GEN-LAST:event_pauloActionPerformed

    private void outroGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outroGerenteActionPerformed
        controlHiago = false;
        controlPaulo = false;
        if (gerente == 3) {
            nomeGerente.setEnabled(true);
            cpfGerente.setEnabled(true);
        }
        if (gerente != 3) {
            gerente = 3;
            if (controlOutroGerente == false) {
                controlOutroGerente = true;
                nomeGerente.setEnabled(true);
                cpfGerente.setEnabled(true);
            } else {
                controlOutroGerente = false;
                nomeGerente.setEnabled(false);
                nomeGerente.setText("");
                cpfGerente.setEnabled(false);
                cpfGerente.setText("");
            }
        }
        controlOutroGerente = true;
    }//GEN-LAST:event_outroGerenteActionPerformed

    private void edmundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edmundoActionPerformed
        controlEdmundo = true;
        controlMarcelo = false;
        controlJuliana = false;
        controlTaciana = false;
        controlOutroAprovacao = false;
        if (aprovacao == 5) {
            controlOutroAprovacao = false;
            nomeAprovacao.setEnabled(false);
            nomeAprovacao.setText("");
            cpfAprovacao.setEnabled(false);
            cpfAprovacao.setText("");
        }
        aprovacao = 1;
    }//GEN-LAST:event_edmundoActionPerformed

    private void marceloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marceloActionPerformed
        controlEdmundo = false;
        controlMarcelo = true;
        controlJuliana = false;
        controlTaciana = false;
        controlOutroAprovacao = false;
        if (aprovacao == 5) {
            controlOutroAprovacao = false;
            nomeAprovacao.setEnabled(false);
            nomeAprovacao.setText("");
            cpfAprovacao.setEnabled(false);
            cpfAprovacao.setText("");
        }
        aprovacao = 2;
    }//GEN-LAST:event_marceloActionPerformed

    private void outroAprovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outroAprovacaoActionPerformed
        controlEdmundo = false;
        controlMarcelo = false;
        controlJuliana = false;
        controlTaciana = false;
        if (aprovacao == 5) {
            nomeAprovacao.setEnabled(true);
            cpfAprovacao.setEnabled(true);
        }
        if (aprovacao != 5) {
            aprovacao = 5;
            if (controlOutroAprovacao == false) {
                controlOutroAprovacao = true;
                nomeAprovacao.setEnabled(true);
                cpfAprovacao.setEnabled(true);
            } else {
                controlOutroAprovacao = false;
                nomeAprovacao.setEnabled(false);
                nomeAprovacao.setText("");
                cpfAprovacao.setEnabled(false);
                cpfAprovacao.setText("");
            }
        }
        controlOutroAprovacao = true;
    }//GEN-LAST:event_outroAprovacaoActionPerformed

    private void julianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_julianaActionPerformed
        controlEdmundo = false;
        controlMarcelo = false;
        controlJuliana = true;
        controlTaciana = false;
        controlOutroAprovacao = false;
        if (aprovacao == 5) {
            controlOutroAprovacao = false;
            nomeAprovacao.setEnabled(false);
            nomeAprovacao.setText("");
            cpfAprovacao.setEnabled(false);
            cpfAprovacao.setText("");
        }
        aprovacao = 3;
    }//GEN-LAST:event_julianaActionPerformed

    private void tacianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacianaActionPerformed
        controlEdmundo = false;
        controlMarcelo = false;
        controlJuliana = false;
        controlTaciana = true;
        controlOutroAprovacao = false;
        if (aprovacao == 5) {
            controlOutroAprovacao = false;
            nomeAprovacao.setEnabled(false);
            nomeAprovacao.setText("");
            cpfAprovacao.setEnabled(false);
            cpfAprovacao.setText("");
        }
        aprovacao = 4;
    }//GEN-LAST:event_tacianaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new N_Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField cpfAprovacao;
    private javax.swing.JTextField cpfGerente;
    private javax.swing.JRadioButton edmundo;
    private javax.swing.JRadioButton hiago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTAno;
    private javax.swing.JTextField jTDia;
    private javax.swing.JTextField jTMes;
    private javax.swing.JTextField jTlocal;
    private javax.swing.JRadioButton juliana;
    private javax.swing.JRadioButton marcelo;
    private javax.swing.JTextField nomeAprovacao;
    private javax.swing.JTextField nomeGerente;
    private javax.swing.JButton ok;
    private javax.swing.JRadioButton outroAprovacao;
    private javax.swing.JRadioButton outroGerente;
    private javax.swing.JRadioButton paulo;
    private javax.swing.JRadioButton taciana;
    // End of variables declaration//GEN-END:variables
}
